### ISSUE TITLE
Custom Cells ?

### ISSUE THREAD

**Issue by ValentinDenis** [LavaSlider/UITableView-Reorder#3]
Hi, I use a custom cell for my table view, which has these properties:

```
#import <UIKit/UIKit.h>
@interface DragAndDropPeopleCell : UITableViewCell
@property (weak, nonatomic) IBOutlet UIImageView *peoplepic;
@property (weak, nonatomic) IBOutlet UILabel *PlaceNum;
@property (weak, nonatomic) IBOutlet UIImageView *CellNumRoundedImage;
@property (weak, nonatomic) IBOutlet UILabel *Name;
@end
```

I'd like to know how to update these outlets instead of juste the cell's text when finishing moving a row
Thanks

**Comment by ValentinDenis** [comment]
Did it with - (void)tableView:(UITableView_)tableView moveRowAtIndexPath:(NSIndexPath_)fromIndexPath toIndexPath:(NSIndexPath*)toIndexPath()

**Comment by LavaSlider** [comment]
Hi ValentinDenis. Glad you figured it out. You solution should be identical to how you would have done it if the cells were being moved in edit mode.
